// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bundleSVC.Data;

namespace bundleSVC.Migrations
{
    [DbContext(typeof(BundleContext))]
    [Migration("20201026141339_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("bundleSVC.Models.Bundle", b =>
                {
                    b.Property<int>("B_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("B_active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("B_availdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("B_expdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("B_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<double>("B_price")
                        .HasColumnType("REAL");

                    b.HasKey("B_code");

                    b.ToTable("Bundles");

                    b.HasData(
                        new
                        {
                            B_code = 1,
                            B_active = true,
                            B_availdate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_expdate = new DateTime(2020, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_name = "test1",
                            B_price = 7.5
                        },
                        new
                        {
                            B_code = 2,
                            B_active = true,
                            B_availdate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_expdate = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_name = "test2",
                            B_price = 12.0
                        },
                        new
                        {
                            B_code = 3,
                            B_active = true,
                            B_availdate = new DateTime(2020, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_expdate = new DateTime(2021, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_name = "test3",
                            B_price = 11.0
                        },
                        new
                        {
                            B_code = 4,
                            B_active = true,
                            B_availdate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_expdate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_name = "test4",
                            B_price = 13.0
                        },
                        new
                        {
                            B_code = 5,
                            B_active = true,
                            B_availdate = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_expdate = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_name = "test5",
                            B_price = 5.0
                        },
                        new
                        {
                            B_code = 6,
                            B_active = true,
                            B_availdate = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_expdate = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            B_name = "test6",
                            B_price = 8.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
